name: Jamie Ly
markdown: kramdown
highlighter: rouge
safe: true
lsi: false
baseurl: /blog
future: true
url: https://jamie.ly/blog
about_me: >
  I am a polyglot, full-stack developer with experience in front-end
  web development, back-end development including RESTful APIs,
  native iOS development, and devops. I am interested in
  software maintainability, functional programming, and game development.