name: Jamie Ly
markdown: kramdown
highlighter: rouge
lsi: false
baseurl: /blog
future: true
url: https://jamie.ly/blog
about_me: >
  I am a polyglot, full-stack developer with experience in front-end
  development, native and cross-platform mobile development, 
  back-end development including RESTful APIs, and devops. I am interested in
  software maintainability, functional programming, and game development.
author:
  twitter: jamiely
feed:
  path: feed.xml
  categories:
    - programming
plugins:
  - jekyll-feed
  - jekyll-paginate-v2

# Settings for jekyll-paginate-v2
pagination:
  enabled: true
  debug: false
  per_page: 10
  trail: 
    before: 2 # The number of links before the current page
    after: 2  # The number of links after the current page